name: Observability Stack Setup

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # -------------------------------
  # Stage 1: Terraform Infrastructure
  # -------------------------------
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::879696522469:role/GitHubActionsCICDRole
          aws-region: eu-north-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      # Import ECS Services into Terraform state
      - name: Terraform Import ECS Services
        run: |
          terraform import aws_ecs_service.prometheus assaabloy-app-cluster/prometheus-service
          terraform import aws_ecs_service.grafana assaabloy-app-cluster/grafana-service
          terraform import aws_ecs_service.cloudwatch_exporter assaabloy-app-cluster/cloudwatch-exporter-service
          terraform import aws_ecs_service.app assaabloy-app-cluster/assaabloy-app-service
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: terraform

  # -------------------------------
  # Stage 2: Observability Setup
  # -------------------------------
  observability:
    runs-on: ubuntu-latest
    needs: terraform   # ensures Stage 1 must succeed before Stage 2 runs
    steps:
      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::879696522469:role/GitHubActionsCICDRole
          aws-region: eu-north-1

      - name: Refresh ECS Services (Prometheus, Grafana, CloudWatch Exporter, App)
        run: |
          aws ecs update-service --cluster assaabloy-app-cluster --service prometheus-service --force-new-deployment
          aws ecs update-service --cluster assaabloy-app-cluster --service grafana-service --force-new-deployment
          aws ecs update-service --cluster assaabloy-app-cluster --service cloudwatch-exporter-service --force-new-deployment
          aws ecs update-service --cluster assaabloy-app-cluster --service assaabloy-app-service --force-new-deployment
